//>>built
(function(e,q){var b,k=function(){},l=function(g){for(var a in g)return 0;return 1},c={}.toString,p=function(g){return"[object Function]"==c.call(g)},h=function(g){return"[object String]"==c.call(g)},f=function(g){return"[object Array]"==c.call(g)},a=function(g,a){if(g)for(var n=0;n<g.length;)a(g[n++])},s=function(g,a){for(var n in a)g[n]=a[n];return g},m=function(g,a){return s(Error(g),{src:"dojoLoader",info:a})},d=1,B=function(){return"_"+d++},r=function(g,a,n){return sa(g,a,n,0,r)},t=this,D=t.document,
y=D&&D.createElement("DiV"),z=r.has=function(g){return p(u[g])?u[g]=u[g](t,D,y):u[g]},u=z.cache=q.hasCache;z.add=function(g,a,n,m){(void 0===u[g]||m)&&(u[g]=a);return n&&z(g)};z.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);z("host-webworker")&&(s(q.hasCache,{"host-browser":0,dom:0,"dojo-dom-ready-api":0,"dojo-sniff":0,"dojo-inject-api":1,"host-webworker":1}),q.loaderPatch={injectUrl:function(g,a){try{importScripts(g),a()}catch(n){}}});for(var v in e.has)z.add(v,
e.has[v],0,1);r.async=1;var K=new Function("return eval(arguments[0]);");r.eval=function(g,a){return K(g+"\r\n//# sourceURL\x3d"+a)};var T={},n=r.signal=function(g,n){var m=T[g];a(m&&m.slice(0),function(g){g.apply(null,f(n)?n:[n])})},L=r.on=function(g,a){var n=T[g]||(T[g]=[]);n.push(a);return{remove:function(){for(var g=0;g<n.length;g++)if(n[g]===a){n.splice(g,1);break}}}},ta=[],Ga={},ua=[],U={},O=r.map={},E=[],H={},I="",w={},A={};v={};var x=0,Y=function(g){var a,n,m,c;for(a in A)n=A[a],(m=a.match(/^url\:(.+)/))?
w["url:"+va(m[1],g)]=n:"*now"==a?c=n:"*noref"!=a&&(m=X(a,g,!0),w[m.mid]=w["url:"+m.url]=n);c&&c(ga(g));A={}},wa=function(g){return g.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(g){return"\\"+g})},C=function(g,a){a.splice(0,a.length);for(var n in g)a.push([n,g[n],RegExp("^"+wa(n)+"(/|$)"),n.length]);a.sort(function(g,a){return a[3]-g[3]});return a},G=function(g,n){a(g,function(g){n.push([h(g[0])?RegExp("^"+wa(g[0])+"$"):g[0],g[1]])})},xa=function(g){var a=g.name;a||(a=g,g={name:a});g=s({main:"main"},
g);g.location=g.location?g.location:a;g.packageMap&&(O[a]=g.packageMap);g.main.indexOf("./")||(g.main=g.main.substring(2));U[a]=g},J=[],P=function(g,m,c){for(var d in g){"waitSeconds"==d&&(r.waitms=1E3*(g[d]||0));"cacheBust"==d&&(I=g[d]?h(g[d])?g[d]:(new Date).getTime()+"":"");if("baseUrl"==d||"combo"==d)r[d]=g[d];g[d]!==u&&(r.rawConfig[d]=g[d],"has"!=d&&z.add("config-"+d,g[d],0,m))}r.baseUrl||(r.baseUrl="./");/\/$/.test(r.baseUrl)||(r.baseUrl+="/");for(d in g.has)z.add(d,g.has[d],0,m);a(g.packages,
xa);for(var b in g.packagePaths)a(g.packagePaths[b],function(g){var a=b+"/"+g;h(g)&&(g={name:g});g.location=a;xa(g)});C(s(O,g.map),E);a(E,function(g){g[1]=C(g[1],[]);"*"==g[0]&&(E.star=g)});C(s(Ga,g.paths),ua);G(g.aliases,ta);if(m)J.push({config:g.config});else for(d in g.config)m=S(d,c),m.config=s(m.config||{},g.config[d]);g.cache&&(Y(),A=g.cache,g.cache["*noref"]&&Y());n("config",[g,r.rawConfig])};if(z("dojo-cdn")){var Q=D.getElementsByTagName("script");b=0;for(var F,M,Z,V;b<Q.length;){F=Q[b++];
if((Z=F.getAttribute("src"))&&(V=Z.match(/(((.*)\/)|^)dojo\.js(\W|$)/i)))M=V[3]||"",q.baseUrl=q.baseUrl||M,x=F;if(Z=F.getAttribute("data-dojo-config")||F.getAttribute("djConfig"))v=r.eval("({ "+Z+" })","data-dojo-config"),x=F}}r.rawConfig={};P(q,1);z("dojo-cdn")&&((U.dojo.location=M)&&(M+="/"),U.dijit.location=M+"../dijit/",U.dojox.location=M+"../dojox/");P(e,1);P(v,1);var $=function(g){ha(function(){a(g.deps,ya)})},sa=function(g,a,n,d,c){var b;if(h(g)){if((b=S(g,d,!0))&&b.executed)return b.result;
if("dojo/i18n"===d.mid)return;throw m("undefinedModule",g);}f(g)||(P(g,0,d),g=a,a=n);if(f(g))if(g.length){n="require*"+B();for(var l,e=[],L=0;L<g.length;)l=g[L++],e.push(S(l,d));b=s(aa("",n,0,""),{injected:2,deps:e,def:a||k,require:d?d.require:r,gc:1});H[b.mid]=b;$(b);var u=W&&0!="sync";ha(function(){ia(b,u)});b.executed||R.push(b);ba()}else a&&a();return c},ga=function(g){if(!g)return r;var a=g.require;a||(a=function(n,d,m){return sa(n,d,m,g,a)},g.require=s(a,r),a.module=g,a.toUrl=function(a){return va(a,
g)},a.toAbsMid=function(a){return ja(a,g)});return a},R=[],ca=[],N={},Ia=function(g){g.injected=1;N[g.mid]=1;g.url&&(N[g.url]=g.pack||1);Ha()},da=function(g){g.injected=2;delete N[g.mid];g.url&&delete N[g.url];l(N)&&Ja()},Ka=r.idle=function(){return!ca.length&&l(N)&&!R.length&&!W},ka=function(g,a){if(a)for(var n=0;n<a.length;n++)if(a[n][2].test(g))return a[n];return 0},za=function(g){var a=[],n,d;for(g=g.replace(/\\/g,"/").split("/");g.length;)n=g.shift(),".."==n&&a.length&&".."!=d?(a.pop(),d=a[a.length-
1]):"."!=n&&a.push(d=n);return a.join("/")},aa=function(g,a,n,d){return{pid:g,mid:a,pack:n,url:d,executed:0,def:0}},Aa=function(g,n,d,c,b,h,s,f,r){var l,B,e,L;L=/^\./.test(g);if(/(^\/)|(\:)|(\.js$)/.test(g)||L&&!n)return aa(0,g,0,g);g=za(L?n.mid+"/../"+g:g);if(/^\./.test(g))throw m("irrationalPath",g);n&&(e=ka(n.mid,h));(e=(e=e||h.star)&&ka(g,e[1]))&&(g=e[1]+g.substring(e[3]));n=(V=g.match(/^([^\/]+)(\/(.+))?$/))?V[1]:"";(l=d[n])?g=n+"/"+(B=V[3]||l.main):n="";var u=0;a(f,function(a){var n=g.match(a[0]);
n&&0<n.length&&(u=p(a[1])?g.replace(a[0],a[1]):a[1])});if(u)return Aa(u,0,d,c,b,h,s,f,r);if(d=c[g])return r?aa(d.pid,d.mid,d.pack,d.url):c[g];c=(e=ka(g,s))?e[1]+g.substring(e[3]):n?l.location+"/"+B:g;/(^\/)|(\:)/.test(c)||(c=b+c);return aa(n,g,l,za(c+".js"))},X=function(g,a,n){return Aa(g,a,U,H,r.baseUrl,n?[]:E,n?[]:ua,n?[]:ta)},Ba=function(g,a,n){return g.normalize?g.normalize(a,function(g){return ja(g,n)}):ja(a,n)},Ca=0,S=function(g,a,n){var d,m;(d=g.match(/^(.+?)\!(.*)$/))?(m=S(d[1],a,n),5===m.executed&&
!m.load&&la(m),m.load?(d=Ba(m,d[2],a),g=m.mid+"!"+(m.dynamic?++Ca+"!":"")+d):(d=d[2],g=m.mid+"!"+ ++Ca+"!waitingForPlugin"),g={plugin:m,mid:g,req:ga(a),prid:d}):g=X(g,a);return H[g.mid]||!n&&(H[g.mid]=g)},ja=r.toAbsMid=function(g,a){return X(g,a).mid},va=r.toUrl=function(g,a){var n=X(g+"/x",a),d=n.url;return Da(0===n.pid?g:d.substring(0,d.length-5))},Ea={injected:2,executed:5,def:3,result:3};M=function(g){return H[g]=s({mid:g},Ea)};var La=M("require"),Ma=M("exports"),Na=M("module"),ea={},ma=0,la=
function(g){var a=g.result;g.dynamic=a.dynamic;g.normalize=a.normalize;g.load=a.load;return g},Oa=function(g){var n={};a(g.loadQ,function(a){var d=Ba(g,a.prid,a.req.module),m=g.dynamic?a.mid.replace(/waitingForPlugin$/,d):g.mid+"!"+d,d=s(s({},a),{mid:m,prid:d,injected:0});H[m]||Fa(H[m]=d);n[a.mid]=H[m];da(a);delete H[a.mid]});g.loadQ=0;var d=function(g){for(var a=g.deps||[],d=0;d<a.length;d++)(g=n[a[d].mid])&&(a[d]=g)},m;for(m in H)d(H[m]);a(R,d)},na=function(g){r.trace("loader-finish-exec",[g.mid]);
g.executed=5;g.defOrder=ma++;g.loadQ&&(la(g),Oa(g));for(b=0;b<R.length;)R[b]===g?R.splice(b,1):b++;/^require\*/.test(g.mid)&&delete H[g.mid]},Pa=[],ia=function(g,a){if(4===g.executed)return r.trace("loader-circular-dependency",[Pa.concat(g.mid).join("-\x3e")]),!g.def||a?ea:g.cjs&&g.cjs.exports;if(!g.executed){if(!g.def)return ea;var n=g.mid,d=g.deps||[],m,c=[],b=0;for(g.executed=4;m=d[b++];){m=m===La?ga(g):m===Ma?g.cjs.exports:m===Na?g.cjs:ia(m,a);if(m===ea)return g.executed=0,r.trace("loader-exec-module",
["abort",n]),ea;c.push(m)}r.trace("loader-run-factory",[g.mid]);n=g.def;c=p(n)?n.apply(null,c):n;g.result=void 0===c&&g.cjs?g.cjs.exports:c;na(g)}return g.result},W=0,ha=function(g){try{W++,g()}finally{W--}Ka()&&n("idle",[])},ba=function(){W||ha(function(){for(var g,a,n=0;n<R.length;)g=ma,a=R[n],ia(a),g!=ma?n=0:n++})};void 0===z("dojo-loader-eval-hint-url")&&z.add("dojo-loader-eval-hint-url",1);var Da="function"==typeof e.fixupUrl?e.fixupUrl:function(g){g+="";return g+(I?(/\?/.test(g)?"\x26":"?")+
I:"")},Fa=function(g){var a=g.plugin;5===a.executed&&!a.load&&la(a);var n=function(a){g.result=a;da(g);na(g);ba()};a.load?a.load(g.prid,g.req,n):a.loadQ?a.loadQ.push(g):(a.loadQ=[g],R.unshift(a),ya(a))},fa=0,oa=0,pa=0,Qa=function(a,n){"function"===typeof e.moduleTextTransform&&(a=e.moduleTextTransform(a,n));z("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));pa=1;a===fa?fa.call(null):r.eval(a,z("dojo-loader-eval-hint-url")?n.url:n.mid);pa=0},ya=function(a){var d=a.mid,c=a.url;if(!a.executed&&
!a.injected&&!(N[d]||a.url&&(a.pack&&N[a.url]===a.pack||1==N[a.url])))if(Ia(a),a.plugin)Fa(a);else{var b=function(){Ra(a);if(2!==a.injected){if(z("dojo-enforceDefine")){n("error",m("noDefine",a));return}da(a);s(a,Ea);r.trace("loader-define-nonmodule",[a.url])}ba()};(fa=w[d]||w["url:"+a.url])?(r.trace("loader-inject",["cache",a.mid,c]),Qa(fa,a),b()):(r.trace("loader-inject",["script",a.mid,c]),oa=a,r.injectUrl(Da(c),b,a),oa=0)}},qa=function(a,d,c){r.trace("loader-define-module",[a.mid,d]);if(2===a.injected)return n("error",
m("multipleDefine",a)),a;s(a,{deps:d,def:c,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(n){a.cjs.exports=n},config:function(){return a.config}}});for(var b=0;d[b];b++)d[b]=S(d[b],a);da(a);!p(c)&&!d.length&&(a.result=c,na(a));return a},Ra=function(n,d){for(var m=[],c,b;ca.length;)b=ca.shift(),d&&(b[0]=d.shift()),c=b[0]&&S(b[0])||n,m.push([c,b[1],b[2]]);Y(n);a(m,function(a){$(qa.apply(null,a))})},Ja=k,Ha=k;z.add("ie-event-behavior",D.attachEvent&&"undefined"===typeof Windows&&("undefined"===
typeof opera||"[object Opera]"!=opera.toString()));var ra=function(a,n,d,m){if(z("ie-event-behavior"))return a.attachEvent(d,m),function(){a.detachEvent(d,m)};a.addEventListener(n,m,!1);return function(){a.removeEventListener(n,m,!1)}},Sa=ra(window,"load","onload",function(){r.pageLoaded=1;"complete"!=D.readyState&&(D.readyState="complete");Sa()}),Q=D.getElementsByTagName("script");for(b=0;!x;)if(!/^dojo/.test((F=Q[b++])&&F.type))x=F;r.injectUrl=function(a,d,c){c=c.node=D.createElement("script");
var b=ra(c,"load","onreadystatechange",function(a){a=a||window.event;var n=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(n.readyState))b(),h(),d&&d()}),h=ra(c,"error","onerror",function(d){b();h();n("error",m("scriptError",[a,d]))});c.type="text/javascript";c.charset="utf-8";c.src=a;x.parentNode.insertBefore(c,x);return c};r.log=k;r.trace=k;F=function(a,d,c){var b=arguments.length,s=["require","exports","module"],f=[0,a,d];1==b?f=[0,p(a)?s:[],a]:2==b&&h(a)?f=[a,p(d)?s:[],d]:3==
b&&(f=[a,d,c]);r.trace("loader-define",f.slice(0,2));if((b=f[0]&&S(f[0]))&&!N[b.mid])$(qa(b,f[1],f[2]));else if(!z("ie-event-behavior")||pa)ca.push(f);else{b=b||oa;if(!b)for(a in N)if((s=H[a])&&s.node&&"interactive"===s.node.readyState){b=s;break}b?(Y(b),$(qa(b,f[1],f[2]))):n("error",m("ieDefineFailed",f[0]));ba()}};F.amd={vendor:"dojotoolkit.org"};s(s(r,q.loaderPatch),e.loaderPatch);L("error",function(a){try{if(a instanceof Error)for(var n in a);}catch(d){}});s(r,{uid:B,cache:w,packs:U});t.define||
(t.define=F,t.require=r,a(J,function(a){P(a)}),L=v.deps||e.deps||q.deps,v=v.callback||e.callback||q.callback,r.boot=L||v?[L||[],v]:0)})(this.dojoConfig||this.djConfig||this.require||{},{async:1,defaultDuration:1,hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:"../dgrid",main:"OnDemandGrid",name:"dgrid"},{location:"../dijit",name:"dijit"},{location:"../spinner",name:"spinner"},{location:"../xstyle",name:"xstyle"},
{location:".",name:"dojo"},{location:"../put-selector",main:"put",name:"put-selector"},{location:"../webview",name:"webview"}],tlmSiblingOfDojo:0});
require({cache:{"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(e,q){var b=document.createElement("div"),k=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector,l=b.querySelectorAll,c=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;e.add("dom-matches-selector",!!k);e.add("dom-qsa",!!l);var p=function(c,m){if(a&&-1<c.indexOf(","))return a(c,m);var d=m?m.ownerDocument||m:q.doc||document,b=(l?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:
/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(c);m=m||d;if(b){if(b[2]){var r=q.byId?q.byId(b[2],d):d.getElementById(b[2]);if(!r||b[1]&&b[1]!=r.tagName.toLowerCase())return[];if(m!=d)for(d=r;d!=m;)if(d=d.parentNode,!d)return[];return b[3]?p(b[3],r):[r]}if(b[3]&&m.getElementsByClassName)return m.getElementsByClassName(b[4]);if(b[5])if(r=m.getElementsByTagName(b[5]),b[4]||b[6])c=(b[4]||"")+b[6];else return r}if(l)return 1===m.nodeType&&"object"!==m.nodeName.toLowerCase()?h(m,
c,m.querySelectorAll):m.querySelectorAll(c);r||(r=m.getElementsByTagName("*"));for(var b=[],d=0,e=r.length;d<e;d++){var k=r[d];1==k.nodeType&&f(k,c,m)&&b.push(k)}return b},h=function(a,b,d){var f=a,h=a.getAttribute("id"),l=h||"__dojo__",e=a.parentNode,k=/^\s*[+~]/.test(b);if(k&&!e)return[];h?l=l.replace(/'/g,"\\$\x26"):a.setAttribute("id",l);k&&e&&(a=a.parentNode);b=b.match(c);for(e=0;e<b.length;e++)b[e]="[id\x3d'"+l+"'] "+b[e];b=b.join(",");try{return d.call(a,b)}finally{h||f.removeAttribute("id")}};
if(!e("dom-matches-selector"))var f=function(){function a(d,b,c){var m=b.charAt(0);if('"'==m||"'"==m)b=b.slice(1,-1);b=b.replace(/\\/g,"");var h=e[c||""];return function(a){return(a=a.getAttribute(d))&&h(a,b)}}function c(a){return function(d,b){for(;(d=d.parentNode)!=b;)if(a(d,b))return!0}}function d(a){return function(d,b){d=d.parentNode;return a?d!=b&&a(d,b):d==b}}function h(a,d){return a?function(b,c){return d(b)&&a(b,c)}:d}var f="div"==b.tagName?"toLowerCase":"toUpperCase",l={"":function(a){a=
a[f]();return function(d){return d.tagName==a}},".":function(a){var d=" "+a+" ";return function(b){return-1<b.className.indexOf(a)&&-1<(" "+b.className+" ").indexOf(d)}},"#":function(a){return function(d){return d.id==a}}},e={"^\x3d":function(a,d){return 0==a.indexOf(d)},"*\x3d":function(a,d){return-1<a.indexOf(d)},"$\x3d":function(a,d){return a.substring(a.length-d.length,a.length)==d},"~\x3d":function(a,d){return-1<(" "+a+" ").indexOf(" "+d+" ")},"|\x3d":function(a,d){return 0==(a+"-").indexOf(d+
"-")},"\x3d":function(a,d){return a==d},"":function(a,d){return!0}},k={};return function(b,f,e){var r=k[f];if(!r){if(f.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,function(b,n,f,e,k,p,q){e?r=h(r,l[f||""](e.replace(/\\/g,""))):n?r=(" "==n?c:d)(r):k&&(r=h(r,a(k,q,p)));return""}))throw Error("Syntax error in query");if(!r)return!0;k[f]=r}return r(b,e)}}();if(!e("dom-qsa"))var a=function(a,b){for(var d=a.match(c),f=
[],h=0;h<d.length;h++){a=new String(d[h].replace(/\s*$/,""));a.indexOf=escape;for(var e=p(a,b),l=0,k=e.length;l<k;l++){var q=e[l];f[q.sourceIndex]=q}}d=[];for(h in f)d.push(f[h]);return d};p.match=k?function(a,b,d){return d&&9!=d.nodeType?h(d,b,function(d){return k.call(a,d)}):k.call(a,b)}:f;return p})},"dojo/_base/window":function(){define(["./kernel","./lang","../sniff"],function(e,q,b){var k={global:e.global,doc:e.global.document||null,body:function(b){b=b||e.doc;return b.body||b.getElementsByTagName("body")[0]},
setContext:function(b,c){e.global=k.global=b;e.doc=k.doc=c},withGlobal:function(b,c,p,h){var f=e.global;try{return e.global=k.global=b,k.withDoc.call(null,b.document,c,p,h)}finally{e.global=k.global=f}},withDoc:function(l,c,p,h){var f=k.doc,a=b("quirks"),s=b("ie"),m,d,B;try{e.doc=k.doc=l;e.isQuirks=b.add("quirks","BackCompat"==e.doc.compatMode,!0,!0);if(b("ie")&&(B=l.parentWindow)&&B.navigator)m=parseFloat(B.navigator.appVersion.split("MSIE ")[1])||void 0,(d=l.documentMode)&&(5!=d&&Math.floor(m)!=
d)&&(m=d),e.isIE=b.add("ie",m,!0,!0);p&&"string"==typeof c&&(c=p[c]);return c.apply(p,h||[])}finally{e.doc=k.doc=f,e.isQuirks=b.add("quirks",a,!0,!0),e.isIE=b.add("ie",s,!0,!0)}}};q.mixin(e,k);return k})},"dojo/_base/lang":function(){define(["./kernel","../has","../sniff"],function(e,q){q.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var b=q("bug-for-in-skips-shadowed")?"hasOwnProperty valueOf isPrototypeOf propertyIsEnumerable toLocaleString toString constructor".split(" "):
[],k=b.length,l=function(a,b,c){c||(c=a[0]&&e.scopeMap[a[0]]?e.scopeMap[a.shift()][1]:e.global);try{for(var d=0;d<a.length;d++){var f=a[d];if(!(f in c))if(b)c[f]={};else return;c=c[f]}return c}catch(h){}},c=Object.prototype.toString,p=function(a,b,c){return(c||[]).concat(Array.prototype.slice.call(a,b||0))},h=/\{([^\}]+)\}/g,f={_extraNames:b,_mixin:function(a,c,m){var d,f,h,e={};for(d in c)if(f=c[d],!(d in a)||a[d]!==f&&(!(d in e)||e[d]!==f))a[d]=m?m(f):f;if(q("bug-for-in-skips-shadowed")&&c)for(h=
0;h<k;++h)if(d=b[h],f=c[d],!(d in a)||a[d]!==f&&(!(d in e)||e[d]!==f))a[d]=m?m(f):f;return a},mixin:function(a,b){a||(a={});for(var c=1,d=arguments.length;c<d;c++)f._mixin(a,arguments[c]);return a},setObject:function(a,b,c){var d=a.split(".");a=d.pop();return(c=l(d,!0,c))&&a?c[a]=b:void 0},getObject:function(a,b,c){return l(a?a.split("."):[],b,c)},exists:function(a,b){return void 0!==f.getObject(a,!1,b)},isString:function(a){return"string"==typeof a||a instanceof String},isArray:function(a){return a&&
(a instanceof Array||"array"==typeof a)},isFunction:function(a){return"[object Function]"===c.call(a)},isObject:function(a){return void 0!==a&&(null===a||"object"==typeof a||f.isArray(a)||f.isFunction(a))},isArrayLike:function(a){return a&&void 0!==a&&!f.isString(a)&&!f.isFunction(a)&&!(a.tagName&&"form"==a.tagName.toLowerCase())&&(f.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!f.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))},extend:function(a,b){for(var c=1,d=arguments.length;c<
d;c++)f._mixin(a.prototype,arguments[c]);return a},_hitchArgs:function(a,b){var c=f._toArray(arguments,2),d=f.isString(b);return function(){var h=f._toArray(arguments),l=d?(a||e.global)[b]:b;return l&&l.apply(a||this,c.concat(h))}},hitch:function(a,b){if(2<arguments.length)return f._hitchArgs.apply(e,arguments);b||(b=a,a=null);if(f.isString(b)){a=a||e.global;if(!a[b])throw['lang.hitch: scope["',b,'"] is null (scope\x3d"',a,'")'].join("");return function(){return a[b].apply(a,arguments||[])}}return!a?
b:function(){return b.apply(a,arguments||[])}},delegate:function(){function a(){}return function(b,c){a.prototype=b;var d=new a;a.prototype=null;c&&f._mixin(d,c);return d}}(),_toArray:q("ie")?function(){function a(a,b,d){d=d||[];for(b=b||0;b<a.length;b++)d.push(a[b]);return d}return function(b){return(b.item?a:p).apply(this,arguments)}}():p,partial:function(a){return f.hitch.apply(e,[null].concat(f._toArray(arguments)))},clone:function(a){if(!a||"object"!=typeof a||f.isFunction(a))return a;if(a.nodeType&&
"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var b,c,d;if(f.isArray(a)){b=[];c=0;for(d=a.length;c<d;++c)c in a&&b.push(f.clone(a[c]))}else b=a.constructor?new a.constructor:{};return f._mixin(b,a,f.clone)},trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,b,c){return a.replace(c||h,f.isFunction(b)?b:function(a,c){return f.getObject(c,
!1,b)})}};f.mixin(e,f);return f})},"dojo/has":function(){define(["require","module"],function(e,q){var b=e.has||function(){};b.add("dom-addeventlistener",!!document.addEventListener);b.add("touch","ontouchstart"in document||"onpointerdown"in document&&0<navigator.maxTouchPoints||window.navigator.msMaxTouchPoints);b.add("touch-events","ontouchstart"in document);b.add("pointer-events","onpointerdown"in document);b.add("MSPointer","msMaxTouchPoints"in navigator);b.add("device-width",screen.availWidth||
innerWidth);var k=document.createElement("form");b.add("dom-attributes-explicit",0==k.attributes.length);b.add("dom-attributes-specified-flag",0<k.attributes.length&&40>k.attributes.length);b.clearElement=function(b){b.innerHTML="";return b};b.normalize=function(e,c){var k=e.match(/[\?:]|[^:\?]*/g),h=0,f=function(a){var c=k[h++];if(":"==c)return 0;if("?"==k[h++]){if(!a&&b(c))return f();f(!0);return f(a)}return c||0};return(e=f())&&c(e)};b.load=function(b,c,e){b?c([b],e):e()};return b})},"dojo/_base/kernel":function(){define(["../has",
"./config","require","module"],function(e,q,b,k){var l;e=function(){return this}();var c={},p={},h={config:q,global:e,dijit:c,dojox:p},c={dojo:["dojo",h],dijit:["dijit",c],dojox:["dojox",p]};k=b.map&&b.map[k.id.match(/[^\/]+/)[0]];for(l in k)c[l]?c[l][0]=k[l]:c[l]=[k[l],{}];for(l in c)k=c[l],k[1]._scopeName=k[0],q.noGlobals||(e[k[0]]=k[1]);h.scopeMap=c;h.baseUrl=h.config.baseUrl=b.baseUrl;h.isAsync=b.async;h.locale=q.locale;q="$Rev: ae6be82 $".match(/[0-9a-f]{7,}/);h.version={major:1,minor:10,patch:3,
flag:"",revision:q?q[0]:NaN,toString:function(){var a=h.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};Function("d","d.eval \x3d function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(h);h.exit=function(){};"undefined"!=typeof console||(console={});b="assert count debug dir dirxml error group groupEnd info profile profileEnd time timeEnd trace warn log".split(" ");var f;for(q=0;f=b[q++];)console[f]||function(){var a=f+"";console[a]="log"in
console?function(){var b=Array.prototype.slice.call(arguments);b.unshift(a+":");console.log(b.join(" "))}:function(){};console[a]._fake=!0}();h.deprecated=h.experimental=function(){};h._hasResource={};return h})},"dojo/promise/Promise":function(){define(["../_base/lang"],function(e){function q(){throw new TypeError("abstract");}return e.extend(function(){},{then:function(b,e,l){q()},cancel:function(b,e){q()},isResolved:function(){q()},isRejected:function(){q()},isFulfilled:function(){q()},isCanceled:function(){q()},
always:function(b){return this.then(b,b)},otherwise:function(b){return this.then(null,b)},trace:function(){return this},traceRejected:function(){return this},toString:function(){return"[object Promise]"}})})},"dojo/query":function(){define("./_base/kernel ./has ./dom ./on ./_base/array ./_base/lang ./selector/_loader ./selector/_loader!default".split(" "),function(e,q,b,k,l,c,p,h){function f(a,d){var c=function(c,n){if("string"==typeof n&&(n=b.byId(n),!n))return new d([]);var f="string"==typeof c?
a(c,n):c?c.end&&c.on?c:[c]:[];return f.end&&f.on?f:new d(f)};c.matches=a.match||function(a,b,d){return 0<c.filter([a],b,d).length};c.filter=a.filter||function(a,b,d){return c(b,d).filter(function(b){return-1<l.indexOf(a,b)})};if("function"!=typeof a){var f=a.search;a=function(a,b){return f(b||document,a)}}return c}q.add("array-extensible",function(){return 1==c.delegate([],{length:1}).length&&!q("bug-for-in-skips-shadowed")});var a=Array.prototype,s=a.slice,m=a.concat,d=l.forEach,B=function(a,b,d){b=
[0].concat(s.call(b,0));d=d||e.global;return function(c){b[0]=c;return a.apply(d,b)}},r=function(a){var b=this instanceof t&&q("array-extensible");"number"==typeof a&&(a=Array(a));var d=a&&"length"in a?a:arguments;if(b||!d.sort){for(var f=b?this:[],h=f.length=d.length,n=0;n<h;n++)f[n]=d[n];if(b)return f;d=f}c._mixin(d,D);d._NodeListCtor=function(a){return t(a)};return d},t=r,D=t.prototype=q("array-extensible")?[]:{};t._wrap=D._wrap=function(a,b,d){a=new (d||this._NodeListCtor||t)(a);return b?a._stash(b):
a};t._adaptAsMap=function(a,b){return function(){return this.map(B(a,arguments,b))}};t._adaptAsForEach=function(a,b){return function(){this.forEach(B(a,arguments,b));return this}};t._adaptAsFilter=function(a,b){return function(){return this.filter(B(a,arguments,b))}};t._adaptWithCondition=function(a,b,d){return function(){var c=arguments,f=B(a,c,d);if(b.call(d||e.global,c))return this.map(f);this.forEach(f);return this}};d(["slice","splice"],function(b){var d=a[b];D[b]=function(){return this._wrap(d.apply(this,
arguments),"slice"==b?this:null)}});d(["indexOf","lastIndexOf","every","some"],function(a){var b=l[a];D[a]=function(){return b.apply(e,[this].concat(s.call(arguments,0)))}});c.extend(r,{constructor:t,_NodeListCtor:t,toString:function(){return this.join(",")},_stash:function(a){this._parent=a;return this},on:function(a,b){var d=this.map(function(d){return k(d,a,b)});d.remove=function(){for(var a=0;a<d.length;a++)d[a].remove()};return d},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},
concat:function(a){var b=s.call(this,0),d=l.map(arguments,function(a){return s.call(a,0)});return this._wrap(m.apply(b,d),this)},map:function(a,b){return this._wrap(l.map(this,a,b),this)},forEach:function(a,b){d(this,a,b);return this},filter:function(a){var b=arguments,d=this,c=0;if("string"==typeof a){d=y._filterResult(this,b[0]);if(1==b.length)return d._stash(this);c=1}return this._wrap(l.filter(d,b[c],b[c+1]),this)},instantiate:function(a,b){var d=c.isFunction(a)?a:c.getObject(a);b=b||{};return this.forEach(function(a){new d(b,
a)})},at:function(){var a=new this._NodeListCtor(0);d(arguments,function(b){0>b&&(b=this.length+b);this[b]&&a.push(this[b])},this);return a._stash(this)}});var y=f(h,r);e.query=f(h,function(a){return r(a)});y.load=function(a,b,d){p.load(a,b,function(a){d(f(a,r))})};e._filterQueryResult=y._filterResult=function(a,b,d){return new r(y.filter(a,b,d))};e.NodeList=y.NodeList=r;return y})},"dojo/selector/_loader":function(){define(["../has","require"],function(e,q){var b=document.createElement("div");e.add("dom-qsa2.1",
!!b.querySelectorAll);e.add("dom-qsa3",function(){try{return b.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e",1==b.querySelectorAll(".TEST:empty").length}catch(e){}});var k;return{load:function(b,c,p,h){h=q;b="default"==b?e("config-selectorEngine")||"css3":b;b="css2"==b||"lite"==b?"./lite":"css2.1"==b?e("dom-qsa2.1")?"./lite":"./acme":"css3"==b?e("dom-qsa3")?"./lite":"./acme":"acme"==b?"./acme":(h=c)&&b;if("?"==b.charAt(b.length-1)){b=b.substring(0,b.length-1);var f=!0}if(f&&(e("dom-compliant-qsa")||
k))return p(k);h([b],function(a){"./lite"!=b&&(k=a);p(a)})}}})},"dojo/parser":function(){define("require ./_base/kernel ./_base/lang ./_base/array ./_base/config ./dom ./_base/window ./_base/url ./aspect ./promise/all ./date/stamp ./Deferred ./has ./query ./on ./ready".split(" "),function(e,q,b,k,l,c,p,h,f,a,s,m,d,B,r,t){function D(a){return eval("("+a+")")}function y(a){var b=a._nameCaseMap,d=a.prototype;if(!b||b._extendCnt<u){var b=a._nameCaseMap={},c;for(c in d)"_"!==c.charAt(0)&&(b[c.toLowerCase()]=
c);b._extendCnt=u}return b}function z(a,d){var c=a.join();if(!v[c]){for(var f=[],h=0,m=a.length;h<m;h++){var r=a[h];f[f.length]=v[r]=v[r]||b.getObject(r)||~r.indexOf("/")&&(d?d(r):e(r))}h=f.shift();v[c]=f.length?h.createSubclass?h.createSubclass(f):h.extend.apply(h,f):h}return v[c]}new Date("X");var u=0;f.after(b,"extend",function(){u++},!0);var v={},K={_clearCache:function(){u++;v={}},_functionFromScript:function(a,b){var d="",c="",f=a.getAttribute(b+"args")||a.getAttribute("args"),h=a.getAttribute("with"),
f=(f||"").split(/\s*,\s*/);h&&h.length&&k.forEach(h.split(/\s*,\s*/),function(a){d+="with("+a+"){";c+="}"});return new Function(f,d+a.innerHTML+c)},instantiate:function(a,b,d){b=b||{};d=d||{};var c=(d.scope||q._scopeName)+"Type",f="data-"+(d.scope||q._scopeName)+"-",h=f+"type",e=f+"mixins",m=[];k.forEach(a,function(a){var d=c in b?b[c]:a.getAttribute(h)||a.getAttribute(c);if(d){var f=a.getAttribute(e),d=f?[d].concat(f.split(/\s*,\s*/)):[d];m.push({node:a,types:d})}});return this._instantiate(m,b,
d)},_instantiate:function(b,d,c,f){function h(a){!d._started&&!c.noStart&&k.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a}b=k.map(b,function(a){var b=a.ctor||z(a.types,c.contextRequire);if(!b)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(b,a.node,d,c,a.scripts,a.inherited)},this);return f?a(b).then(h):h(b)},construct:function(a,c,e,m,l,p){function t(a){z&&b.setObject(z,a);for(A=0;A<J.length;A++)f[J[A].advice||
"after"](a,J[A].method,b.hitch(a,J[A].func),!0);for(A=0;A<P.length;A++)P[A].call(a);for(A=0;A<Q.length;A++)a.watch(Q[A].prop,Q[A].func);for(A=0;A<F.length;A++)r(a,F[A].event,F[A].func);return a}var O=a&&a.prototype;m=m||{};var E={};m.defaults&&b.mixin(E,m.defaults);p&&b.mixin(E,p);var u;d("dom-attributes-explicit")?u=c.attributes:d("dom-attributes-specified-flag")?u=k.filter(c.attributes,function(a){return a.specified}):(p=(/^input$|^img$/i.test(c.nodeName)?c:c.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,
"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),u=k.map(p.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,value:"LI"==c.nodeName&&"value"==a||"enctype"==b?c.getAttribute(b):c.getAttributeNode(b).value}}));var I=m.scope||q._scopeName;p="data-"+I+"-";var w={};"dojo"!==I&&(w[p+"props"]="data-dojo-props",w[p+"type"]="data-dojo-type",w[p+"mixins"]="data-dojo-mixins",w[I+"type"]="dojoType",w[p+"id"]="data-dojo-id");for(var A=0,x,I=[],z,v;x=u[A++];){var C=x.name,G=C.toLowerCase();
x=x.value;switch(w[G]||G){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":v=x;break;case "data-dojo-id":case "jsid":z=x;break;case "data-dojo-attach-point":case "dojoattachpoint":E.dojoAttachPoint=x;break;case "data-dojo-attach-event":case "dojoattachevent":E.dojoAttachEvent=x;break;case "class":E["class"]=c.className;break;case "style":E.style=c.style&&c.style.cssText;break;default:if(C in O||(C=y(a)[G]||C),C in O)switch(typeof O[C]){case "string":E[C]=
x;break;case "number":E[C]=x.length?Number(x):NaN;break;case "boolean":E[C]="false"!=x.toLowerCase();break;case "function":""===x||-1!=x.search(/[^\w\.]+/i)?E[C]=new Function(x):E[C]=b.getObject(x,!1)||new Function(x);I.push(C);break;default:G=O[C],E[C]=G&&"length"in G?x?x.split(/\s*,\s*/):[]:G instanceof Date?""==x?new Date(""):"now"==x?new Date:s.fromISOString(x):G instanceof h?q.baseUrl+x:D(x)}else E[C]=x}}for(u=0;u<I.length;u++)w=I[u].toLowerCase(),c.removeAttribute(w),c[w]=null;if(v)try{v=D.call(m.propsThis,
"{"+v+"}"),b.mixin(E,v)}catch(K){throw Error(K.toString()+" in data-dojo-props\x3d'"+v+"'");}b.mixin(E,e);l||(l=a&&(a._noScript||O._noScript)?[]:B("\x3e script[type^\x3d'dojo/']",c));var J=[],P=[],Q=[],F=[];if(l)for(A=0;A<l.length;A++)w=l[A],c.removeChild(w),e=w.getAttribute(p+"event")||w.getAttribute("event"),m=w.getAttribute(p+"prop"),v=w.getAttribute(p+"method"),I=w.getAttribute(p+"advice"),u=w.getAttribute("type"),w=this._functionFromScript(w,p),e?"dojo/connect"==u?J.push({method:e,func:w}):"dojo/on"==
u?F.push({event:e,func:w}):E[e]=w:"dojo/aspect"==u?J.push({method:v,advice:I,func:w}):"dojo/watch"==u?Q.push({prop:m,func:w}):P.push(w);a=(l=a.markupFactory||O.markupFactory)?l(E,c,a):new a(E,c);return a.then?a.then(t):t(a)},scan:function(a,b){function d(a){if(!a.inherited){a.inherited={};var b=a.node,c=d(a.parent),b={dir:b.getAttribute("dir")||c.dir,lang:b.getAttribute("lang")||c.lang,textDir:b.getAttribute(B)||c.textDir},n;for(n in b)b[n]&&(a.inherited[n]=b[n])}return a.inherited}var c=[],f=[],
h={},r=(b.scope||q._scopeName)+"Type",l="data-"+(b.scope||q._scopeName)+"-",p=l+"type",B=l+"textdir",l=l+"mixins",s=a.firstChild,t=b.inherited;if(!t){var D=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&D(a.parentNode,b)},t={dir:D(a,"dir"),lang:D(a,"lang"),textDir:D(a,B)},u;for(u in t)t[u]||delete t[u]}for(var t={inherited:t},y,v;;)if(s)if(1!=s.nodeType)s=s.nextSibling;else if(y&&"script"==s.nodeName.toLowerCase())(C=s.getAttribute("type"))&&/^dojo\/\w/i.test(C)&&y.push(s),
s=s.nextSibling;else if(v)s=s.nextSibling;else{var C=s.getAttribute(p)||s.getAttribute(r);u=s.firstChild;if(!C&&(!u||3==u.nodeType&&!u.nextSibling))s=s.nextSibling;else{v=null;if(C){var G=s.getAttribute(l);y=G?[C].concat(G.split(/\s*,\s*/)):[C];try{v=z(y,b.contextRequire)}catch(K){}v||k.forEach(y,function(a){~a.indexOf("/")&&!h[a]&&(h[a]=!0,f[f.length]=a)});G=v&&!v.prototype._noScript?[]:null;t={types:y,ctor:v,parent:t,node:s,scripts:G};t.inherited=d(t);c.push(t)}else t={node:s,scripts:y,parent:t};
y=G;v=s.stopParser||v&&v.prototype.stopParser&&!b.template;s=u}}else{if(!t||!t.node)break;s=t.node.nextSibling;v=!1;t=t.parent;y=t.scripts}var J=new m;f.length?(b.contextRequire||e)(f,function(){J.resolve(k.filter(c,function(a){if(!a.ctor)try{a.ctor=z(a.types,b.contextRequire)}catch(d){}for(var c=a.parent;c&&!c.types;)c=c.parent;var f=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(f&&f.stopParser&&!b.template);a.instantiate=!c||c.instantiate&&c.instantiateChildren;return a.instantiate}))}):J.resolve(c);
return J.promise},_require:function(a,d){var c=D("{"+a.innerHTML+"}"),f=[],h=[],r=new m,l=d&&d.contextRequire||e,k;for(k in c)f.push(k),h.push(c[k]);l(h,function(){for(var a=0;a<f.length;a++)b.setObject(f[a],arguments[a]);r.resolve(arguments)});return r.promise},_scanAmd:function(a,b){var d=new m,c=d.promise;d.resolve(!0);var f=this;B("script[type\x3d'dojo/require']",a).forEach(function(a){c=c.then(function(){return f._require(a,b)});a.parentNode.removeChild(a)});return c},parse:function(a,d){var f;
!d&&a&&a.rootNode?(d=a,f=d.rootNode):a&&b.isObject(a)&&!("nodeType"in a)?d=a:f=a;f=f?c.byId(f):p.body();d=d||{};var h=d.template?{template:!0}:{},e=[],m=this,r=this._scanAmd(f,d).then(function(){return m.scan(f,d)}).then(function(a){return m._instantiate(a,h,d,!0)}).then(function(a){return e=e.concat(a)}).otherwise(function(a){throw a;});b.mixin(e,r);return e}};q.parser=K;l.parseOnLoad&&t(100,K,"parse");return K})},"dojo/errors/create":function(){define(["../_base/lang"],function(e){return function(q,
b,k,l){k=k||Error;var c=function(e){if(k===Error){Error.captureStackTrace&&Error.captureStackTrace(this,c);var h=Error.call(this,e),f;for(f in h)h.hasOwnProperty(f)&&(this[f]=h[f]);this.message=e;this.stack=h.stack}else k.apply(this,arguments);b&&b.apply(this,arguments)};c.prototype=e.delegate(k.prototype,l);c.prototype.name=q;return c.prototype.constructor=c}})},"dojo/_base/array":function(){define(["./kernel","../has","./lang"],function(e,q,b){function k(a){return p[a]=new Function("item","index",
"array",a)}function l(a){var b=!a;return function(c,d,f){var h=0,e=c&&c.length||0,l;e&&"string"==typeof c&&(c=c.split(""));"string"==typeof d&&(d=p[d]||k(d));if(f)for(;h<e;++h){if(l=!d.call(f,c[h],h,c),a^l)return!l}else for(;h<e;++h)if(l=!d(c[h],h,c),a^l)return!l;return b}}function c(a){var b=1,c=0,d=0;a||(b=c=d=-1);return function(e,l,k,p){if(p&&0<b)return f.lastIndexOf(e,l,k);p=e&&e.length||0;var q=a?p+d:c;k===h?k=a?c:p+d:0>k?(k=p+k,0>k&&(k=c)):k=k>=p?p+d:k;for(p&&"string"==typeof e&&(e=e.split(""));k!=
q;k+=b)if(e[k]==l)return k;return-1}}var p={},h,f={every:l(!1),some:l(!0),indexOf:c(!0),lastIndexOf:c(!1),forEach:function(a,b,c){var d=0,f=a&&a.length||0;f&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=p[b]||k(b));if(c)for(;d<f;++d)b.call(c,a[d],d,a);else for(;d<f;++d)b(a[d],d,a)},map:function(a,b,c,d){var f=0,h=a&&a.length||0;d=new (d||Array)(h);h&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=p[b]||k(b));if(c)for(;f<h;++f)d[f]=b.call(c,a[f],f,a);else for(;f<h;++f)d[f]=
b(a[f],f,a);return d},filter:function(a,b,c){var d=0,f=a&&a.length||0,h=[],e;f&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=p[b]||k(b));if(c)for(;d<f;++d)e=a[d],b.call(c,e,d,a)&&h.push(e);else for(;d<f;++d)e=a[d],b(e,d,a)&&h.push(e);return h},clearCache:function(){p={}}};b.mixin(e,f);return f})},"dojo/dom":function(){define(["./sniff","./_base/window"],function(e,q){if(7>=e("ie"))try{document.execCommand("BackgroundImageCache",!1,!0)}catch(b){}var k={};e("ie")?k.byId=function(b,e){if("string"!=
typeof b)return b;var h=e||q.doc,f=b&&h.getElementById(b);if(f&&(f.attributes.id.value==b||f.id==b))return f;h=h.all[b];if(!h||h.nodeName)h=[h];for(var a=0;f=h[a++];)if(f.attributes&&f.attributes.id&&f.attributes.id.value==b||f.id==b)return f}:k.byId=function(b,e){return("string"==typeof b?(e||q.doc).getElementById(b):b)||null};k.isDescendant=function(b,e){try{b=k.byId(b);for(e=k.byId(e);b;){if(b==e)return!0;b=b.parentNode}}catch(h){}return!1};e.add("css-user-select",function(b,e,h){if(!h)return!1;
b=h.style;e=["Khtml","O","Moz","Webkit"];h=e.length;var f="userSelect";do if("undefined"!==typeof b[f])return f;while(h--&&(f=e[h]+"UserSelect"));return!1});var l=e("css-user-select");k.setSelectable=l?function(b,e){k.byId(b).style[l]=e?"":"none"}:function(b,e){b=k.byId(b);var h=b.getElementsByTagName("*"),f=h.length;if(e)for(b.removeAttribute("unselectable");f--;)h[f].removeAttribute("unselectable");else for(b.setAttribute("unselectable","on");f--;)h[f].setAttribute("unselectable","on")};return k})},
"dojo/sniff":function(){define(["./has"],function(e){var q=navigator,b=q.userAgent,q=q.appVersion,k=parseFloat(q);e.add("air",0<=b.indexOf("AdobeAIR"));e.add("msapp",parseFloat(b.split("MSAppHost/")[1])||void 0);e.add("khtml",0<=q.indexOf("Konqueror")?k:void 0);e.add("webkit",parseFloat(b.split("WebKit/")[1])||void 0);e.add("chrome",parseFloat(b.split("Chrome/")[1])||void 0);e.add("safari",0<=q.indexOf("Safari")&&!e("chrome")?parseFloat(q.split("Version/")[1]):void 0);e.add("mac",0<=q.indexOf("Macintosh"));
e.add("quirks","BackCompat"==document.compatMode);if(b.match(/(iPhone|iPod|iPad)/)){var l=RegExp.$1.replace(/P/,"p"),c=b.match(/OS ([\d_]+)/)?RegExp.$1:"1",c=parseFloat(c.replace(/_/,".").replace(/_/g,""));e.add(l,c);e.add("ios",c)}e.add("android",parseFloat(b.split("Android ")[1])||void 0);e.add("bb",(0<=b.indexOf("BlackBerry")||0<=b.indexOf("BB10"))&&parseFloat(b.split("Version/")[1])||void 0);e.add("trident",parseFloat(q.split("Trident/")[1])||void 0);e.add("svg","undefined"!==typeof SVGAngle);
e("webkit")||(0<=b.indexOf("Opera")&&e.add("opera",9.8<=k?parseFloat(b.split("Version/")[1])||k:k),0<=b.indexOf("Gecko")&&(!e("khtml")&&!e("webkit")&&!e("trident"))&&e.add("mozilla",k),e("mozilla")&&e.add("ff",parseFloat(b.split("Firefox/")[1]||b.split("Minefield/")[1])||void 0),document.all&&!e("opera")&&(b=parseFloat(q.split("MSIE ")[1])||void 0,(q=document.documentMode)&&(5!=q&&Math.floor(b)!=q)&&(b=q),e.add("ie",b)),e.add("wii","undefined"!=typeof opera&&opera.wiiremote));return e})},"dojo/_base/config":function(){define(["../has",
"require"],function(e,q){var b={},k=q.rawConfig,l;for(l in k)b[l]=k[l];if(!b.locale&&"undefined"!=typeof navigator&&(k=navigator.language||navigator.userLanguage))b.locale=k.toLowerCase();return b})},"dojo/errors/CancelError":function(){define(["./create"],function(e){return e("CancelError",null,null,{dojoType:"cancel"})})},"dojo/Deferred":function(){define(["./has","./_base/lang","./errors/CancelError","./promise/Promise","require"],function(e,q,b,k,l){var c=Object.freeze||function(){},p=function(a,
b,c,f,e){for(e=0;e<a.length;e++)h(a[e],b,c,f)},h=function(b,d,c,e){e=b[d];var h=b.deferred;if(e)try{var k=e(c);0===d?"undefined"!==typeof k&&a(h,d,k):k&&"function"===typeof k.then?(b.cancel=k.cancel,k.then(f(h,1),f(h,2),f(h,0))):a(h,1,k)}catch(l){a(h,2,l)}else a(h,d,c)},f=function(b,d){return function(c){a(b,d,c)}},a=function(a,b,c){if(!a.isCanceled())switch(b){case 0:a.progress(c);break;case 1:a.resolve(c);break;case 2:a.reject(c)}},s=function(a){var d=this.promise=new k,f=this,e,l,q=!1,y=[];this.isResolved=
d.isResolved=function(){return 1===e};this.isRejected=d.isRejected=function(){return 2===e};this.isFulfilled=d.isFulfilled=function(){return!!e};this.isCanceled=d.isCanceled=function(){return q};this.progress=function(a,b){if(e){if(!0===b)throw Error("This deferred has already been fulfilled.");return d}p(y,0,a,null,f);return d};this.resolve=function(a,b){if(e){if(!0===b)throw Error("This deferred has already been fulfilled.");return d}p(y,e=1,l=a,null,f);y=null;return d};var z=this.reject=function(a,
b){if(e){if(!0===b)throw Error("This deferred has already been fulfilled.");return d}p(y,e=2,l=a,void 0,f);y=null;return d};this.then=d.then=function(a,b,c){var f=[c,a,b];f.cancel=d.cancel;f.deferred=new s(function(a){return f.cancel&&f.cancel(a)});e&&!y?h(f,e,l,void 0):y.push(f);return f.deferred.promise};this.cancel=d.cancel=function(d,c){if(e){if(!0===c)throw Error("This deferred has already been fulfilled.");}else{if(a){var f=a(d);d="undefined"===typeof f?d:f}q=!0;if(e){if(2===e&&l===d)return d}else return"undefined"===
typeof d&&(d=new b),z(d),d}};c(d)};s.prototype.toString=function(){return"[object Deferred]"};l&&l(s);return s})},"dojo/_base/url":function(){define(["./kernel"],function(e){var q=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,b=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,k=function(){for(var e=arguments,c=[e[0]],p=1;p<e.length;p++)if(e[p]){var h=new k(e[p]+""),c=new k(c[0]+"");if(""==h.path&&!h.scheme&&!h.authority&&!h.query)null!=h.fragment&&(c.fragment=h.fragment),
h=c;else if(!h.scheme&&(h.scheme=c.scheme,!h.authority&&(h.authority=c.authority,"/"!=h.path.charAt(0)))){for(var c=(c.path.substring(0,c.path.lastIndexOf("/")+1)+h.path).split("/"),f=0;f<c.length;f++)"."==c[f]?f==c.length-1?c[f]="":(c.splice(f,1),f--):0<f&&(!(1==f&&""==c[0])&&".."==c[f]&&".."!=c[f-1])&&(f==c.length-1?(c.splice(f,1),c[f-1]=""):(c.splice(f-1,2),f-=2));h.path=c.join("/")}c=[];h.scheme&&c.push(h.scheme,":");h.authority&&c.push("//",h.authority);c.push(h.path);h.query&&c.push("?",h.query);
h.fragment&&c.push("#",h.fragment)}this.uri=c.join("");e=this.uri.match(q);this.scheme=e[2]||(e[1]?"":null);this.authority=e[4]||(e[3]?"":null);this.path=e[5];this.query=e[7]||(e[6]?"":null);this.fragment=e[9]||(e[8]?"":null);null!=this.authority&&(e=this.authority.match(b),this.user=e[3]||null,this.password=e[4]||null,this.host=e[6]||e[7],this.port=e[9]||null)};k.prototype.toString=function(){return this.uri};return e._Url=k})},"dojo/aspect":function(){define([],function(){function e(b,c,a,e){var m=
b[c],d="around"==c,l;if(d){var r=a(function(){return m.advice(this,arguments)});l={remove:function(){r&&(r=b=a=null)},advice:function(a,b){return r?r.apply(a,b):m.advice(a,b)}}}else l={remove:function(){if(l.advice){var d=l.previous,e=l.next;!e&&!d?delete b[c]:(d?d.next=e:b[c]=e,e&&(e.previous=d));b=a=l.advice=null}},id:k++,advice:a,receiveArguments:e};if(m&&!d)if("after"==c){for(;m.next&&(m=m.next););m.next=l;l.previous=m}else"before"==c&&(b[c]=l,l.next=m,m.previous=l);else b[c]=l;return l}function q(c){return function(f,
a,l,m){var d=f[a],p;if(!d||d.target!=f)f[a]=p=function(){for(var a=k,d=arguments,c=p.before;c;)d=c.advice.apply(this,d)||d,c=c.next;if(p.around)var e=p.around.advice(this,d);for(c=p.after;c&&c.id<a;){if(c.receiveArguments)var f=c.advice.apply(this,d),e=f===b?e:f;else e=c.advice.call(this,e,d);c=c.next}return e},d&&(p.around={advice:function(a,b){return d.apply(a,b)}}),p.target=f;f=e(p||d,c,l,m);l=null;return f}}var b,k=0,l=q("after"),c=q("before"),p=q("around");return{before:c,around:p,after:l}})},
"dojo/when":function(){define(["./Deferred","./promise/Promise"],function(e,q){return function(b,k,l,c){var p=b&&"function"===typeof b.then,h=p&&b instanceof q;if(p)h||(p=new e(b.cancel),b.then(p.resolve,p.reject,p.progress),b=p.promise);else return 1<arguments.length?k?k(b):b:(new e).resolve(b);return k||l||c?b.then(k,l,c):b}})},"dojo/date/stamp":function(){define(["../_base/lang","../_base/array"],function(e,q){var b={};e.setObject("dojo.date.stamp",b);b.fromISOString=function(e,l){b._isoRegExp||
(b._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/);var c=b._isoRegExp.exec(e),p=null;if(c){c.shift();c[1]&&c[1]--;c[6]&&(c[6]*=1E3);l&&(l=new Date(l),q.forEach(q.map("FullYear Month Date Hours Minutes Seconds Milliseconds".split(" "),function(a){return l["get"+a]()}),function(a,b){c[b]=c[b]||a}));p=new Date(c[0]||1970,c[1]||0,c[2]||1,c[3]||0,c[4]||0,c[5]||0,c[6]||0);100>c[0]&&p.setFullYear(c[0]||1970);var h=0,f=c[7]&&c[7].charAt(0);
"Z"!=f&&(h=60*(c[8]||0)+(Number(c[9])||0),"-"!=f&&(h*=-1));f&&(h-=p.getTimezoneOffset());h&&p.setTime(p.getTime()+6E4*h)}return p};b.toISOString=function(b,e){var c=function(a){return 10>a?"0"+a:a};e=e||{};var p=[],h=e.zulu?"getUTC":"get",f="";"time"!=e.selector&&(f=b[h+"FullYear"](),f=["0000".substr((f+"").length)+f,c(b[h+"Month"]()+1),c(b[h+"Date"]())].join("-"));p.push(f);if("date"!=e.selector){f=[c(b[h+"Hours"]()),c(b[h+"Minutes"]()),c(b[h+"Seconds"]())].join(":");h=b[h+"Milliseconds"]();e.milliseconds&&
(f+="."+(100>h?"0":"")+c(h));if(e.zulu)f+="Z";else if("time"!=e.selector)var h=b.getTimezoneOffset(),a=Math.abs(h),f=f+((0<h?"-":"+")+c(Math.floor(a/60))+":"+c(a%60));p.push(f)}return p.join("T")};return b})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(e,q,b){function k(a,d,c,e,k){if(e=d.match(/(.*):(.*)/))return d=e[2],e=e[1],h.selector(e,d).call(k,a,c);b("touch")&&(f.test(d)&&(c=T(c)),!b("event-orientationchange")&&"orientationchange"==
d&&(d="resize",a=window,c=T(c)));B&&(c=B(c));if(a.addEventListener){var l=d in m,p=l?m[d]:d;a.addEventListener(p,c,l);return{remove:function(){a.removeEventListener(p,c,l)}}}if(y&&a.attachEvent)return y(a,"on"+d,c);throw Error("Target must be an event emitter");}function l(){this.cancelable=!1;this.defaultPrevented=!0}function c(){this.bubbles=!1}var p=window.ScriptEngineMajorVersion;b.add("jscript",p&&p()+ScriptEngineMinorVersion()/10);b.add("event-orientationchange",b("touch")&&!b("android"));b.add("event-stopimmediatepropagation",
window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);b.add("event-focusin",function(a,b,d){return"onfocusin"in d});b("touch")&&b.add("touch-can-modify-event-delegate",function(){var a=function(){};a.prototype=document.createEvent("MouseEvents");try{var b=new a;b.target=null;return null===b.target}catch(d){return!1}});var h=function(a,b,d,c){return"function"==typeof a.on&&"function"!=typeof b&&!a.nodeType?a.on(b,d):h.parse(a,b,d,k,c,this)};h.pausable=function(a,
b,d,c){var e;a=h(a,b,function(){if(!e)return d.apply(this,arguments)},c);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};h.once=function(a,b,d,c){var e=h(a,b,function(){e.remove();return d.apply(this,arguments)});return e};h.parse=function(a,b,d,c,e,f){if(b.call)return b.call(f,a,d);if(b instanceof Array)k=b;else if(-1<b.indexOf(","))var k=b.split(/\s*,\s*/);if(k){var l=[];b=0;for(var m;m=k[b++];)l.push(h.parse(a,m,d,c,e,f));l.remove=function(){for(var a=0;a<l.length;a++)l[a].remove()};
return l}return c(a,b,d,e,f)};var f=/^touch/;h.matches=function(a,b,d,c,e){e=e&&e.matches?e:q.query;c=!1!==c;1!=a.nodeType&&(a=a.parentNode);for(;!e.matches(a,b,d);)if(a==d||!1===c||!(a=a.parentNode)||1!=a.nodeType)return!1;return a};h.selector=function(a,b,d){return function(c,e){function f(b){return h.matches(b,a,c,d,k)}var k="function"==typeof a?{matches:a}:this,l=b.bubble;return l?h(c,l(f),e):h(c,b,function(a){var b=f(a.target);if(b)return e.call(b,a)})}};var a=[].slice,s=h.emit=function(b,d,
e){var f=a.call(arguments,2),h="on"+d;if("parentNode"in b){var k=f[0]={},m;for(m in e)k[m]=e[m];k.preventDefault=l;k.stopPropagation=c;k.target=b;k.type=d;e=k}do b[h]&&b[h].apply(b,f);while(e&&e.bubbles&&(b=b.parentNode));return e&&e.cancelable&&e},m=b("event-focusin")?{}:{focusin:"focus",focusout:"blur"};if(!b("event-stopimmediatepropagation"))var d=function(){this.modified=this.immediatelyStopped=!0},B=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=d,a.apply(this,
arguments)}};if(b("dom-addeventlistener"))h.emit=function(a,b,d){if(a.dispatchEvent&&document.createEvent){var c=(a.ownerDocument||document).createEvent("HTMLEvents");c.initEvent(b,!!d.bubbles,!!d.cancelable);for(var e in d)e in c||(c[e]=d[e]);return a.dispatchEvent(c)&&c}return s.apply(h,arguments)};else{h._fixEvent=function(a,b){a||(a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event);if(!a)return a;try{r&&(a.type==r.type&&a.srcElement==r.target)&&(a=r)}catch(d){}if(!a.target)switch(a.target=
a.srcElement,a.currentTarget=b||a.srcElement,"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=a.toElement),a.stopPropagation||(a.stopPropagation=z,a.preventDefault=u),a.type){case "keypress":var c="charCode"in a?a.charCode:a.keyCode;10==c?(c=0,a.keyCode=13):13==c||27==c?c=0:3==c&&(c=99);a.charCode=c;c=a;c.keyChar=c.charCode?String.fromCharCode(c.charCode):"";c.charOrCode=c.keyChar||c.keyCode}return a};var r,t=function(a){this.handle=a};t.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};
var D=function(a){return function(b){b=h._fixEvent(b,this);var d=a.call(this,b);b.modified&&(r||setTimeout(function(){r=null}),r=b);return d}},y=function(a,d,c){c=D(c);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>b("jscript"))&&!b("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var f=a[d];if(!f||!f.listeners){var h=f,f=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");
f.listeners=[];a[d]=f;f.global=this;h&&f.listeners.push(_dojoIEListeners_.push(h)-1)}f.listeners.push(a=f.global._dojoIEListeners_.push(c)-1);return new t(a)}return e.after(a,d,c,!0)},z=function(){this.cancelBubble=!0},u=h._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}if(b("touch"))var v=function(){},K=window.orientation,T=function(a){return function(d){var c=d.corrected;if(!c){var e=
d.type;try{delete d.type}catch(f){}if(d.type){if(b("touch-can-modify-event-delegate"))v.prototype=d,c=new v;else{var c={},h;for(h in d)c[h]=d[h]}c.preventDefault=function(){d.preventDefault()};c.stopPropagation=function(){d.stopPropagation()}}else c=d,c.type=e;d.corrected=c;if("resize"==e){if(K==window.orientation)return null;K=window.orientation;c.type="orientationchange";return a.call(this,c)}"rotation"in c||(c.rotation=0,c.scale=1);var e=c.changedTouches[0],k;for(k in e)delete c[k],c[k]=e[k]}return a.call(this,
c)}};return h})},"dojo/domReady":function(){define(["./has"],function(e){function q(a){f.push(a);h&&b()}function b(){if(!a){for(a=!0;f.length;)try{f.shift()(l)}catch(b){}a=!1;q._onQEmpty()}}var k=function(){return this}(),l=document,c={loaded:1,complete:1},p="string"!=typeof l.readyState,h=!!c[l.readyState],f=[],a;q.load=function(a,b,d){q(d)};q._Q=f;q._onQEmpty=function(){};p&&(l.readyState="loading");if(!h){var s=[],m=function(a){a=a||k.event;h||"readystatechange"==a.type&&!c[l.readyState]||(p&&
(l.readyState="complete"),h=1,b())},d=function(a,b){a.addEventListener(b,m,!1);f.push(function(){a.removeEventListener(b,m,!1)})};if(!e("dom-addeventlistener")){var d=function(a,b){b="on"+b;a.attachEvent(b,m);f.push(function(){a.detachEvent(b,m)})},B=l.createElement("div");try{B.doScroll&&null===k.frameElement&&s.push(function(){try{return B.doScroll("left"),1}catch(a){}})}catch(r){}}d(l,"DOMContentLoaded");d(k,"load");"onreadystatechange"in l?d(l,"readystatechange"):p||s.push(function(){return c[l.readyState]});
if(s.length){var t=function(){if(!h){for(var a=s.length;a--;)if(s[a]()){m("poller");return}setTimeout(t,30)}};t()}}return q})},"dojo/ready":function(){define(["./_base/kernel","./has","require","./domReady","./_base/lang"],function(e,q,b,k,l){var c=0,p=[],h=0;q=function(){c=1;e._postLoad=e.config.afterOnLoad=!0;f()};var f=function(){if(!h){for(h=1;c&&(!k||0==k._Q.length)&&(b.idle?b.idle():1)&&p.length;){var a=p.shift();try{a()}catch(d){if(d.info=d.message,b.signal)b.signal("error",d);else throw d;
}}h=0}};b.on&&b.on("idle",f);k&&(k._onQEmpty=f);var a=e.ready=e.addOnLoad=function(a,b,c){var h=l._toArray(arguments);"number"!=typeof a?(c=b,b=a,a=1E3):h.shift();c=c?l.hitch.apply(e,h):function(){b()};c.priority=a;for(h=0;h<p.length&&a>=p[h].priority;h++);p.splice(h,0,c);f()},s=e.config.addOnLoad;if(s)a[l.isArray(s)?"apply":"call"](e,s);k?k(q):q();return a})},"dojo/promise/all":function(){define(["../_base/array","../Deferred","../when"],function(e,q,b){var k=e.some;return function(e){var c,p;e instanceof
Array?p=e:e&&"object"===typeof e&&(c=e);var h,f=[];if(c){p=[];for(var a in c)Object.hasOwnProperty.call(c,a)&&(f.push(a),p.push(c[a]));h={}}else p&&(h=[]);if(!p||!p.length)return(new q).resolve(h);var s=new q;s.promise.always(function(){h=f=null});var m=p.length;k(p,function(a,e){c||f.push(e);b(a,function(a){s.isFulfilled()||(h[f[e]]=a,0===--m&&s.resolve(h))},s.reject);return s.isFulfilled()});return s.promise}})}}});
(function(){var e=this.require;e({cache:{}});!e.async&&e(["dojo"]);e.boot&&e.apply(null,e.boot)})();
//# sourceMappingURL=dojo.js.map